---
- hosts: all
  become: true

  vars_files:
  - private-variables.yml

  vars:
    ansible_user: chip
    ansible_ssh_pass: chip

    ntp_timezone: Europe/Berlin
    ntp_manage_config: true
    ntp_servers:
     - ptbtime1.ptb.de iburst
     - ptbtime2.ptb.de iburst
     - ptbtime3.ptb.de iburst

    unattended_origins_patterns:
      - 'origin=Debian,codename=${distro_codename},label=Debian'
    unattended_automatic_reboot_time: "04:10"

  roles:
    - freifunk-monitor
    - nerab.chip
    - nerab.rsyslog-patch
    - geerlingguy.ntp
    - jnv.unattended-upgrades
